### ISSUE TITLE
Install master-specific modules.

### ISSUE THREAD

**Issue by mcollina** [Level/party#1]
I often use the [level-ttl](https://www.npmjs.org/package/level-ttl) module, which I must attach only once in the 'master' process. What is the right approach? I think this use case is not handled at the moment.

I can't just add a `'promoted'` event, as I need to intercept the creation of the new database. So, if it's ok for you I'll add a `wrapMaster` option with a function to install the master-only modules. So we can replace this line
https://github.com/substack/level-party/blob/master/index.js#L54
with:

``` javascript
proxy.swap(opts.wrapMaster && opts.wrapMaster(db) || db);
```

Shall I submit a PR?

**Comment by vweevers** [comment]
Is this still an issue, or can it be closed?
