### ISSUE TITLE
level-party leader process holding memory

### ISSUE THREAD

**Issue by maxlath** [Level/party#36]
### env
- OS: ubuntu 20.04
- node: v16.13.1
- level-party: v5.1.1
- leveldown options: none

### problem
Our level-party leader process holds up to 3GB of RAM, and refuses to release it once the activity peak passes, before being eventually killed by Linux OOM Killer (See https://github.com/inventaire/inventaire/issues/542)

It's actually probably not a `level-party`-specific issue, as trying to run with only `level` produces the same behavior, but I didn't know where to post: would that be a `leveldown` issue? Is that an expected amount of RAM for leveldb with the default options? Any clue on what we can try to address this?

Thanks for any help, I'm running short of ideas ^^'

**Comment by vweevers** [comment]
> Is that an expected amount of RAM for leveldb with the default options

No, but it depends on what you're doing. Do you have some code to share?

**Comment by maxlath** [comment]
We have several modules making use of their own sub databases, see
- [`get_sub_db.js`](https://github.com/inventaire/inventaire/blob/master/server/db/level/get_sub_db.js) which returns a `subleveldown`-wrapped db handle
- [different modules calling that `get_sub_db.js`](https://github.com/inventaire/inventaire/search?q=get_sub_db) to do their thing in different encoding, mostly json and utf8
- the most suspicious thing I can think of would be [our use](https://github.com/inventaire/inventaire/blob/master/server/db/level/jobs.js) of [`level-jobs`](https://github.com/pgte/level-jobs), a lib that was not updated in the last 4 years, but disabling the code relying on it (thus not even loading the module) did not seem to reduce the amount of RAM used

**Comment by vweevers** [comment]
Have you ruled out [cacheSize](https://github.com/inventaire/inventaire/blob/18fe6ccf874313e7774f2b317661f207d110ea12/server/db/level/get_sub_db.js#L16) and [maxOpenFiles](https://github.com/inventaire/inventaire/blob/18fe6ccf874313e7774f2b317661f207d110ea12/server/db/level/get_sub_db.js#L30)?

**Comment by maxlath** [comment]
yes, both options are [disabled](https://github.com/inventaire/inventaire/commit/046f6976125011689e41ffb8d283b65d5e17e904) in the currently running process based on [this branch](https://github.com/inventaire/inventaire/commits/level-party-leader)

**Comment by vweevers** [comment]
The rest of it is too much code to go over.

> Any clue on what we can try to address this?

Use a memory profiler, starting with the JS side because that's easier.

**Comment by maxlath** [comment]
yes, I tried to use `heapdump`, but struggle to get any useful information out of the result. Thanks for the input, I'll keep digging

**Comment by maxlath** [comment]
I wonder if this might be related to those issues with mmap in LevelDB repo https://github.com/google/leveldb/issues/860 https://github.com/google/leveldb/issues/866: would there be a way to customize mmap limit from leveldown? (I guess not, as the answer in the issue is to fork leveldb :/)

**Comment by vweevers** [comment]
> would there be a way to customize mmap limit from leveldown?

Not via JS, but if you just want to confirm that mmap is the issue, you could clone the leveldown repo, tweak relevant LevelDB code (which is vendored into leveldown), build leveldown and see if it makes any difference. I think the relevant code is:

https://github.com/Level/leveldown/blob/4b97662b55df9e2c6a0ac9d5f4b221ecb3e861f7/deps/leveldb/leveldb-1.20/util/env_posix.cc#L574-L582

**Comment by maxlath** [comment]
I [tried](https://github.com/inventaire/leveldown/commit/c119508) setting `mmap_limit = 0`, but while it does successfully prevent to mmap files, the huge memory allocation is still there. So it seems I'm back to looking for clues.

Inspired by https://github.com/vectordotdev/vector/issues/7514, I went on to profile the memory allocation using [valgrind](https://valgrind.org/) (in my case, the command was `valgrind --tool=massif node ./scripts/level_party_leader.js`). Here is the report data generated after a process holding between 2 and 4GB of RAM was shut down to let [`level_party_leader.js`](https://github.com/inventaire/inventaire/blob/level-party-leader/scripts/level_party_leader.js) take the lead (a process that just joins the level-party and does nothing else). The memory went to the roof (4GB) as it was, I guess, taking over the tasks started by the previous level-party leader(?). I then SIGINT it to get it to generate the massif data report: 
[massif.out.538201.inventaire.prod.zip](https://github.com/Level/party/files/8604153/massif.out.538201.inventaire.prod.zip)

Giving that report to [massif-visualizer](https://apps.kde.org/fr/massif-visualizer/), gives the following visualization:
![massif](https://user-images.githubusercontent.com/1596934/166266650-e88631ee-267b-42fa-b7bc-457fbbd184d3.png). If anyone has a clue what could possibly make those functions allocate so much memory, I'm interested :sweat_smile:

**Comment by maxlath** [comment]
I'm delighted to announce that this issue seems solved :sweat_smile:

I went into details of the issue in the commit message here https://github.com/inventaire/inventaire/commit/4141906b7ea47fcbb6bf374104648706949b4db8 but here is a summary of what might be of interest for level-party:

An error in our code was making us build batch operations arrays with a big array mistakenly passed as an operation key. Somewhere between levelup `batch` function and abstratct-leveldown `batch` function, that array operation key was turned into a buffer, and the batch operations went on without throwing an error.

Is this an expected behavior to be able to pass an array as a batch operation key? If yes:
- That issue can be closed, and sorry for bothering
- Is there a way to optionally choose to forbid that? Is it possible to customize `_serializeKey` from a level-party db object, to make it reject an array passed as a key?

----

Minimum code to reproduce it:
```js
const db = require('level-party')('/tmp/foo')

db.batch([
  {
    type: 'del',
    // This key will be converted to "foo,bar", no error will be raised
    // 'level' has the same behavior
    key: [ 'foo', 'bar' ]
  }
])
.then(res => console.log('success', res))
.catch(err => console.error('error', err))
```

**Comment by vweevers** [comment]
Glad to hear you found the issue, congrats!

> Is this an expected behavior to be able to pass an array as a batch operation key?

Sort of, yes. It depends on the encoding. In this case the key goes through the `utf8` encoding which just does `String(key)`.

In general, encodings don't validate input, in order to be fast and forgiving. They massage user input into a desired type. For example, `db.get(Buffer.from('3'))` and `db.get(3)` and `db.get('3')` all do the same thing. I'm not sure to what extent that's by design (historically) but it's fitting for JavaScript.

You could opt-in to stricter type checking by using TypeScript.

> Is it possible to customize _serializeKey?

Encodings are applied before `_serializeKey()` so at that point your array key has already been converted to a string. Side note: the `_serializeKey` method no longer exists in [`abstract-level`](https://github.com/Level/abstract-level).
