### ISSUE TITLE
Can level-party be used with RocksDB?

### ISSUE THREAD

**Issue by maxlath** [Level/party#47]
I'm getting a bit lost with all those layers: is there a way to pass a rocksdb version of abstract-leveldown? I have the impression that it's not possible, but maybe I'm missing something?

**Comment by vweevers** [comment]
Not out of the box, no. Some pointers:

- You can fork `level-party` and swap [this](https://github.com/Level/party/blob/ab4448247e0e1fcfb205a95f623f6fc9443a2cd0/index.js#L3)
- These are old modules. Among others, `level-party` is superseded by [`rave-level`](https://github.com/Level/rave-level).
- You could similarly fork `rave-level`
- If you don't need leader election, you could use [`many-level`](https://github.com/Level/many-level) directly which accepts almost any `abstract-level` database
- If you only need _read_ access from multiple processes, RocksDB does support that, removing the need for parties and raves.

**Comment by maxlath** [comment]
Thanks for the pointers!
