### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by binarykitchen** [Level/party#48]
Good evening,

Wondering if this cool library is still maintained after two years?

Understand, we are all busy. The change from Level v7 to v8, has this ever been considered?

Thanks,
M.

**Comment by vweevers** [comment]
Superseded by https://github.com/Level/rave-level, didn't update the README yet (PR welcome).

**Comment by binarykitchen** [comment]
@vweevers Thanks for the prompt response.

I'm on `"level-party": "5.1.1"`, any breaking changes to switch to rave-level?

**Comment by vweevers** [comment]
We have an upgrade here (for replacing `level-party` with `rave-level`): https://github.com/Level/rave-level/blob/main/UPGRADING.md

**Comment by binarykitchen** [comment]
(thanks mate, I'll check out tomorrow - New Zealand here)

**Comment by binarykitchen** [comment]
@vweevers Finally migrated to rave-level and the upgrade wasn't too painful. All works well. Thanks for the advice
