### ISSUE TITLE
lev and level-party

### ISSUE THREAD

**Issue by mattstyles** [Level/party#9]
Howdy,

```
lev -r --port ~/.party.lev/level-party.sock
```

I've been using [lev](https://github.com/hij1nx/lev) to connect to a partied level instance while level-party is connected to it by connecting to the socket, this worked in v1.0.1 but not is 2.x.

I've no idea where the issue is, `lev` just uses `net.connect` to connect to the socket, but do you know any work around that would make this work? Sorry its a bit vague, I'm also making an assumption you're at least a little familiar with lev.

I should probably clarify that `net.connect` does actually connect to the socket, but any operation to query the db just hangs.

I guess a different approach would be if anyone knows a CLI that would let me poke around with the db with a level-party instance is connected?

**Comment by mafintosh** [comment]
lev and leveldown 2.0 uses a different wire protocol which is probably why this doesn't work. when i have some free time i'll look into seeing how hard it would be to support both in lev

**Comment by mattstyles** [comment]
Cool, thanks for the quick response. I'll have a look too, although suspect you will be faster...

**Comment by 0x00A** [comment]
This can be closed. level-party is working properly in lev now. No special arguments required.
